crop_size = (100, 100)
input_images_dir = './Data/img'
input_masks_dir = './Data/final_masks'
max_depth = 4
crops_per_image = 15
max_shift_for_fix = 20
min_shift_for_fix = 3
formats = ['png', 'jpeg', 'jpg']
output_dir = './Output/generated_training_data'
output_img_data = './Output/generated_training_data/images'
output_mask_data = './Output/generated_training_data/annotations'
output_img_extraction = './Output/objects_extraction/transparent'
output_mask_extraction = './Output/objects_extraction/annotations'
fake_data_artifacts_amount = 3000
object_placeholder_imgs_dir = 'Data/fake_data/img'
object_placeholder_masks_dir = 'Data/fake_data/masks'
#object_img_dir = './Output/objects_extraction/images'
object_img_dir = './Output/objects_extraction/transparent'
object_mask_dir = './Output/objects_extraction/annotations'
filter_size = 300
background_prob = 0.1
color_elimination_const = 33
HZ_preprocess = True
